insert into clients_comment_components (title, text, likes) values ('aliquet ultrices', null, 329);
insert into clients_comment_components (title, text, likes) values ('aliquam quis', null, 180);
insert into clients_comment_components (title, text, likes) values ('morbi ut odio', null, 180);
insert into clients_comment_components (title, text, likes) values ('libero non', null, 206);
insert into clients_comment_components (title, text, likes) values ('ac neque', null, 21);
insert into clients_comment_components (title, text, likes) values ('aenean lectus', null, 344);
insert into clients_comment_components (title, text, likes) values ('purus', null, 352);
insert into clients_comment_components (title, text, likes) values ('purus', null, 49);
insert into clients_comment_components (title, text, likes) values ('ultrices posuere', null, 484);
insert into clients_comment_components (title, text, likes) values ('velit vivamus', null, 219);
insert into clients_comment_components (title, text, likes) values ('eu orci', null, 102);
insert into clients_comment_components (title, text, likes) values ('suscipit', null, 324);
insert into clients_comment_components (title, text, likes) values ('ipsum', null, 182);
insert into clients_comment_components (title, text, likes) values ('nulla justo aliquam', null, 177);
insert into clients_comment_components (title, text, likes) values ('lacus', null, 213);
insert into clients_comment_components (title, text, likes) values ('id sapien', null, 127);
insert into clients_comment_components (title, text, likes) values ('vestibulum velit id', null, 448);
insert into clients_comment_components (title, text, likes) values ('urna', null, 223);
insert into clients_comment_components (title, text, likes) values ('magna at', null, 395);
insert into clients_comment_components (title, text, likes) values ('est risus', null, 126);
insert into clients_comment_components (title, text, likes) values ('eu tincidunt in', null, 374);
insert into clients_comment_components (title, text, likes) values ('at', null, 182);
insert into clients_comment_components (title, text, likes) values ('luctus tincidunt nulla', null, 321);
insert into clients_comment_components (title, text, likes) values ('diam cras', null, 136);
insert into clients_comment_components (title, text, likes) values ('justo nec condimentum', null, 25);
insert into clients_comment_components (title, text, likes) values ('parturient', null, 441);
insert into clients_comment_components (title, text, likes) values ('ipsum aliquam', null, 150);
insert into clients_comment_components (title, text, likes) values ('in faucibus', null, 190);
insert into clients_comment_components (title, text, likes) values ('posuere cubilia curae', null, 28);
insert into clients_comment_components (title, text, likes) values ('nulla', null, 49);
insert into clients_comment_components (title, text, likes) values ('accumsan', null, 268);
insert into clients_comment_components (title, text, likes) values ('sed vel', null, 434);
insert into clients_comment_components (title, text, likes) values ('faucibus', null, 439);
insert into clients_comment_components (title, text, likes) values ('nunc', null, 125);
insert into clients_comment_components (title, text, likes) values ('lacinia', null, 31);
insert into clients_comment_components (title, text, likes) values ('cursus', null, 439);
insert into clients_comment_components (title, text, likes) values ('congue', null, 418);
insert into clients_comment_components (title, text, likes) values ('amet', null, 412);
insert into clients_comment_components (title, text, likes) values ('vel nulla', null, 479);
insert into clients_comment_components (title, text, likes) values ('sollicitudin mi sit', null, 231);
insert into clients_comment_components (title, text, likes) values ('luctus et', null, 159);
insert into clients_comment_components (title, text, likes) values ('lacinia nisi', null, 137);
insert into clients_comment_components (title, text, likes) values ('dapibus', null, 151);
insert into clients_comment_components (title, text, likes) values ('diam in', null, 64);
insert into clients_comment_components (title, text, likes) values ('vivamus metus arcu', null, 256);
insert into clients_comment_components (title, text, likes) values ('maecenas tincidunt', null, 172);
insert into clients_comment_components (title, text, likes) values ('arcu sed augue', null, 319);
insert into clients_comment_components (title, text, likes) values ('curabitur in libero', null, 186);
insert into clients_comment_components (title, text, likes) values ('turpis nec euismod', null, 360);
insert into clients_comment_components (title, text, likes) values ('interdum eu tincidunt', null, 186);
insert into clients_comment_components (title, text, likes) values ('sit amet', null, 444);
insert into clients_comment_components (title, text, likes) values ('consequat lectus in', null, 88);
insert into clients_comment_components (title, text, likes) values ('felis ut at', null, 144);
insert into clients_comment_components (title, text, likes) values ('amet nulla quisque', null, 299);
insert into clients_comment_components (title, text, likes) values ('vestibulum sagittis sapien', null, 444);
insert into clients_comment_components (title, text, likes) values ('nonummy integer', null, 10);
insert into clients_comment_components (title, text, likes) values ('at dolor quis', null, 313);
insert into clients_comment_components (title, text, likes) values ('odio justo', null, 413);
insert into clients_comment_components (title, text, likes) values ('orci eget', null, 456);
insert into clients_comment_components (title, text, likes) values ('eu orci', null, 264);
insert into clients_comment_components (title, text, likes) values ('ac', null, 293);
insert into clients_comment_components (title, text, likes) values ('elementum', null, 76);
insert into clients_comment_components (title, text, likes) values ('morbi', null, 188);
insert into clients_comment_components (title, text, likes) values ('tempor convallis nulla', null, 203);
insert into clients_comment_components (title, text, likes) values ('eros', null, 339);
insert into clients_comment_components (title, text, likes) values ('dui maecenas', null, 76);
insert into clients_comment_components (title, text, likes) values ('lacinia', null, 192);
insert into clients_comment_components (title, text, likes) values ('pede lobortis ligula', null, 76);
insert into clients_comment_components (title, text, likes) values ('orci', null, 401);
insert into clients_comment_components (title, text, likes) values ('in faucibus', null, 487);
insert into clients_comment_components (title, text, likes) values ('est', null, 255);
insert into clients_comment_components (title, text, likes) values ('non', null, 121);
insert into clients_comment_components (title, text, likes) values ('sapien dignissim vestibulum', null, 182);
insert into clients_comment_components (title, text, likes) values ('ultrices libero', null, 267);
insert into clients_comment_components (title, text, likes) values ('sed', null, 262);
insert into clients_comment_components (title, text, likes) values ('quisque porta volutpat', null, 61);
insert into clients_comment_components (title, text, likes) values ('lacus', null, 426);
insert into clients_comment_components (title, text, likes) values ('justo etiam', null, 141);
insert into clients_comment_components (title, text, likes) values ('dis parturient', null, 267);
insert into clients_comment_components (title, text, likes) values ('curae', null, 99);
insert into clients_comment_components (title, text, likes) values ('libero', null, 293);
insert into clients_comment_components (title, text, likes) values ('maecenas', null, 466);
insert into clients_comment_components (title, text, likes) values ('quisque erat eros', null, 69);
insert into clients_comment_components (title, text, likes) values ('vestibulum rutrum', null, 153);
insert into clients_comment_components (title, text, likes) values ('eget eros', null, 346);
insert into clients_comment_components (title, text, likes) values ('quisque erat eros', null, 48);
insert into clients_comment_components (title, text, likes) values ('aliquam non mauris', null, 444);
insert into clients_comment_components (title, text, likes) values ('pretium iaculis', null, 485);
insert into clients_comment_components (title, text, likes) values ('luctus', null, 225);
insert into clients_comment_components (title, text, likes) values ('fusce congue diam', null, 192);
insert into clients_comment_components (title, text, likes) values ('non mattis', null, 369);
insert into clients_comment_components (title, text, likes) values ('amet erat', null, 190);
insert into clients_comment_components (title, text, likes) values ('at feugiat', null, 216);
insert into clients_comment_components (title, text, likes) values ('augue', null, 356);
insert into clients_comment_components (title, text, likes) values ('aliquet', null, 191);
insert into clients_comment_components (title, text, likes) values ('lorem', null, 99);
insert into clients_comment_components (title, text, likes) values ('in faucibus orci', null, 430);
insert into clients_comment_components (title, text, likes) values ('volutpat', null, 248);
insert into clients_comment_components (title, text, likes) values ('morbi', null, 177);
insert into clients_comment_components (title, text, likes) values ('cum', null, 50);
