insert into categories (name) values ('Motherboard');
insert into categories (name) values ('Processor');
insert into categories (name) values ('Graphic card');
insert into categories (name) values ('RAM');
insert into categories (name) values ('Case');
insert into categories (name) values ('Power suply');
insert into categories (name) values ('HDD');
insert into categories (name) values ('SSD');
insert into categories (name) values ('Cooling');
insert into categories (name) values ('Screen');